name: Beaconomics
version: '1.0.0-BETA'
main: com.swondi.beaconomics.Beaconomics
api-version: '1.21'
authors: [ Francesco Macaluso ]
website: https://swondi.com
commands:
  spawn:
    description: Teleports to spawn
    usage: /spawn
  bugreport:
    description: Handles all bug-report related commands
    usage: /bugreport [category] [description]
  team:
    description: Handles all team related commands
    usage: /team [add|create|kick]
  enderchest:
    aliases:
    - "ec"
    description: Handles all enderchest related commands
    usage: /enderchest
  bank:
    description: Handles all money related commands
    usage: /bank [deposit|withdraw|pay|info|upgrade]
  balancetop:
    description: Top n player balance
    usage: /balancetop
    aliases: [baltop]
  kits:
    description: Shows all available kits and their cooldown
    usage: /kits
  kit:
    description: Handles all kit related commands
    usage: /kit [starter]
  shop:
    description: Handles all shop related commands
    usage: /shop
  sethome:
    description: Handles player possibility to set a home
    usage: /sethome
  spawn:
    description: Command for teleport the player to the spawn
    usage: /spawn
  nexus:
    aliases:
    - "base"
    description: Handle Nexus Home teleport
    usage: /nexus
  system:
    description: Handles all UI related command
    usage: ""
  admin:
    description: Admin commands
    usage: ""

permissions:
  beaconomics.bugreport.create:
    description: Allows the player to create bug reports
    default: true
  beaconomics.enderchest.use:
    description: Allows the player to use the Starter Kit
    default: op
  beaconomics.kit.bypasscooldown:
    description: Bypasses the kit cooldown
    default: op
  beaconomics.kit.starter:
    description: Allows the player to use the Starter Kit
    default: true
  beaconomics.kit.inferno:
    description: Allows the player to use the Inferno Kit
    default: op
  beaconomics.kit.fire:
    description: Allows the player to use the Fire Kit
    default: op
  beaconomics.kit.ember:
    description: Allows the player to use the Ember Kit
    default: op
  beaconomics.kit.blaze:
    description: Allows the player to use the Blaze Kit
    default: op
  beaconomics.kit.spark:
    description: Allows the player to use the Spark Kit
    default: op
